### ISSUE TITLE
get the windows working

### ISSUE THREAD

**Issue by BradleyScrim** [BradleyScrim/table-validator#8]
- right now it's a mess
- `validation_drop_target.py`

# ToDo
- [ ] get rid of the window animations
- [ ] find good sizes
- [ ] make windows movable by user
- [ ] check, if it's working with more the one monitor…
